# Generated by Django 4.2.1 on 2023-06-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codesa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('guests', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
